services:
  nginx:
    build: ./requirements/nginx
    image: nginx:nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    ports:
      - "443:443"
      # - "80:80"
      - "81:81"
    networks:
      - inception
    depends_on:
      - wordpress

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:wordpress
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: aakhrif@aakhrif
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb_vol:
    driver_opts:
      type: none
      device: /home/aakhrif/data/mariadb
      o: bind
  wordpress_vol:
    driver_opts:
      type: none
      device: /home/aakhrif/data/wordpress
      o: bind
