services:
  nginx:
    build: ./requirements/nginx
    image: nginx:nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - wordpress_vol:/var/www/html/wordpress
      - phpmyadmin_vol:/var/www/html/phpmyadmin
    ports:
      - "443:443"
      - "80:80"
      - "81:81"
    networks:
      - inception
    depends_on:
      - wordpress
  mariadb:
    build:  ./requirements/mariadb
    image: mariadb:mariadb
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
  wordpress:
    build:  ./requirements/wordpress
    image: wordpress:wordpress
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - wordpress_vol:/var/www/html/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    env_file:
      - .env
  # phpmyadmin:
  #   build: ./requirements/phpmyadmin
  #   image: phpmyadmin:phpmyadmin
  #   container_name: phpmyadmin
  #   retart: unless-stopped
  #   volumes:
  #     - phpmyadmin_vol:/var/www/html/phpmyadmin
  #   networks:
  #     - inception
  #   depends_on:
  #     - mariadb
  #     - nginx
  #   env_file:
  #     - .env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=aakhrif@aakhrif
      - MYSQL_DATABASE=cloud_1
      - MYSQL_USER=aakhrif
      - MYSQL_PASSWORD=aakhrif@aakhrif
    # volumes:
      - ./requirements/phpmyadmin/config.inc.php:/var/www/html
    ports:
      - "8080:80"
    networks:
      - inception

networks:
  inception:
    driver : bridge

volumes:
  mariadb_vol:
    driver_opts:
      type: none
      device: /home/aakhrif/data/mariadb
      o: bind
  wordpress_vol:
    driver_opts:
      type: none
      device: /home/aakhrif/data/wordpress
      o: bind
  phpmyadmin_vol:
    driver_opts:
      type: none
      device: /home/aakhrif/data/phpmyadmin
      o: bind