---
- name: install requirements
  import_playbook: ./requirements.yaml
  tags: install_requirements

- name: cloud-1
  hosts: host
  tasks:
    - name: copy inception into the cloud machine
      synchronize:
        src: ../../inception/
        dest: /home/inception
        delete: no
        recursive: yes
        checksum: yes
      notify: rebuild infra

  handlers:
    - name: rebuild infra
      command: make re
      args:
        chdir: /home/inception/

- name: run jobs
  import_playbook: ./run.yaml
  tags: run_job
