---
- name: installing dependencies
  hosts: host
  become: yes
  tasks:
    - name: updating packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      
    - name: installing docker and make
      apt:
        name:
          - docker.io
          - make
        state: present
      when: ansible_os_family == "Debian"
      
    - name: start and enable docker service
      systemd:
        name: docker
        state: started
        enabled: yes
        
    - name: add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
        
    # - name: install docker compose
    #   get_url:
    #     url: "https://github.com/docker/compose/releases/latest/download/docker-compose-{{ ansible_system }}-{{ ansible_machine }}"
    #     dest: /usr/local/bin/docker-compose
    #     mode: '0755'
    #     owner: root
    #     group: root
        
    # - name: create docker-compose symlink (optional)
    #   file:
    #     src: /usr/local/bin/docker-compose
    #     dest: /usr/bin/docker-compose
    #     state: link
        
    # - name: verify docker compose installation
    #   command: docker-compose --version
    #   register: docker_compose_version
      
    # - name: display docker compose version
    #   debug:
    #     msg: "Docker Compose installed: {{ docker_compose_version.stdout }}"